language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -r tests/requirements.txt --use-mirrors
script: 
  - flake8 --ignore=F401 twilio
  - flake8 --ignore=E123,E126,E128,E501 tests
  - nosetests
